[build]
builder = "NIXPACKS"
buildCommand = "npm ci --omit=dev && npm run build"
variables = { NODE_VERSION = "24" }

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

